name: build-and-deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

env:
  K8S_NAMESPACE: demo
  CREATE_PULL_SECRET: "false"   # set to "true" if your image is private

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute lowercase owner/repo (GHCR requires lowercase)
        run: |
          echo "OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "REPO_LC=$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "IMAGE=ghcr.io/$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')/$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}
            ${{ env.IMAGE }}:latest
          build-args: |
            COMMIT_SHA=${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout manifests
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      # 🔑 write DECODED kubeconfig from base64 secret
      - name: Write kubeconfig from secret
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      # ✅ quick sanity check so we don't debug blind
      - name: Verify kubeconfig works
        run: |
          echo "Bytes in kubeconfig: $(wc -c < $HOME/.kube/config)"
          kubectl config get-contexts
          kubectl cluster-info

      # Recompute IMAGE vars in this job (envs don't carry over from previous job automatically)
      - name: Compute lowercase owner/repo (for IMAGE)
        run: |
          echo "OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "REPO_LC=$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Ensure namespace exists
        run: |
          kubectl get ns "${{ env.K8S_NAMESPACE }}" >/dev/null 2>&1 || \
          kubectl create ns "${{ env.K8S_NAMESPACE }}"

      # Optional: create pull secret for private GHCR images
      - name: (Optional) Create GHCR imagePullSecret
        if: env.CREATE_PULL_SECRET == 'true'
        env:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          kubectl -n "${{ env.K8S_NAMESPACE }}" get secret ghcr-pull >/dev/null 2>&1 || \
          kubectl -n "${{ env.K8S_NAMESPACE }}" create secret docker-registry ghcr-pull \
            --docker-server=ghcr.io \
            --docker-username="$GHCR_USERNAME" \
            --docker-password="$GHCR_TOKEN"

      # Apply your manifests (adjust paths if they live under k8s/)
      - name: Apply manifests
        run: |
          kubectl -n "${{ env.K8S_NAMESPACE }}" apply -f hello-deployment.yaml
          kubectl -n "${{ env.K8S_NAMESPACE }}" apply -f hello-service.yaml
          kubectl -n "${{ env.K8S_NAMESPACE }}" apply -f hello-ingress.yaml

      - name: Patch deployment to current image (commit SHA)
        env:
          IMAGE: ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}
          SHA: ${{ github.sha }}
        run: |
          CONTAINER=$(kubectl -n "${{ env.K8S_NAMESPACE }}" get deploy hello -o jsonpath='{.spec.template.spec.containers[0].name}')
          kubectl -n "${{ env.K8S_NAMESPACE }}" set image deployment/hello "$CONTAINER=${IMAGE}:${SHA}" --record

      - name: Wait for rollout
        run: |
          kubectl -n "${{ env.K8S_NAMESPACE }}" rollout status deployment/hello --timeout=180s

